apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
  namespace: chatty-app
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongo-service
  replicas: 2
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-pv
          mountPath: /data/db
  

      volumes:
      - name: mongo-pv
        persistentVolumeClaim:
          claimName: mongo-pvc